#!/usr/bin/env python3

import pymysql

"""
def genebank():


    This is a dummy function that returns a list of entries. The real code should
    return a list of lists and would access the MySQL database
    """


"""
    cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession, gene_id, location, dna_seq, aa_seq'
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)

    connection.close()



def get_proteinid():
    
    """gets gene information from database
       return: A SQL query returning a summary list of protein product names. Accession, gene_id, location, dna_seq, aa_seq, protein_id
    
    
    """
    
   cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession, gene_id, location, dna_seq, aa_seq'
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)

    connection.close()
    
    
def get_accessionno():
    
    """
    gets gene information through accession number
       input:accession number
       return: Returned will be a list containing with corresponding gene information that has an accession code.
       Gene information will be present in a tuple. 
    Accession, gene_id, location, dna_seq, aa_seq, protein_id
    """
    
   cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession, gene_id, location, dna_seq, aa_seq'
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)

    connection.close()
    
    
 def get_proteinaccessionno():
    
    """gets protein information through accession number
       input:accession number
       return: Accession, gene_id, location, dna_seq, aa_seq, protein_id
    """
    
   cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession, gene_id, location, dna_seq, aa_seq'
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)

    connection.close()
    
 
def get_geneid():
    
    """fetch gene information through gene identifier 
       input:gene_id
       return: SQL query returning a list of gene, Accession, gene_id, location, dna_seq, aa_seq, protein_id
    """
    
   cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession, gene_id, location, dna_seq, aa_seq'
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)

    connection.close()
    
    
