#!/usr/bin/env python3

import pymysql

"""
def all_genebank():


    This is a dummy function that returns a list of entries. The real code should
    return a list of lists and would access the MySQL database
    """


"""
    cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession, gene_id, location, dna_seq, aa_seq'
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)

    connection.close()



def get_proteinnames():
    
    """gets gene information from database
       return: A SQL query returning a summary list of protein product names. Accession, gene_id, location, dna_seq, aa_seq, protein_id
    
    
    """
    
   cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT DISTINCT product \
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)

    connection.close()
    
    
def get_accessionno():
    
    """
    gets gene information through accession number
       input:accession number
       return: Returned will be a list of accession numbers.
    """
    
   cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession'
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)

    connection.close()
    
    
 def get_chrom_loc():
    
   """
    SQL query returning a list of chromosomal locations
    """
    
   cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession, location'
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)

    connection.close()
    
 
def get_geneid():
    
    """fetch gene information through gene identifier 
       input:gene_id
       return: SQL query returning a list of genes.
    """
    
   cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession, gene_id, '
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)
    


def get_CDS():
    """
    Output:Returns a list of CDS records and would access the MySQL database
    """
   cursorObject        = connectionObject.cursor() 
    sqlquery= 'SELECT Accession, gene_id, '
    cursorObject.execute(sqlQuery)
    rows                = cursorObject.fetchall()

    for row in rows:
    yield(row)
    

    connection.close()
    
    
