#!/usr/bin/env python3

"""
Program: Genebank parser
Date Created: 1st of April 2022
Author: Janani Govindarasan
Function: Grep relevant information from genebank file and populate mysql database. 
Description:
This program reads the genbank chromosome 7 file and regex the following for each entry:
accession number, gene_id, location , product, CDS, amino acid sequence and dna sequence. 
""""


import sys
sys.path.insert(0, "..")
import db_parser
import config as cf
import pymysql.cursors


connection = pymysql.connect(cf.mysql["host"], cf.mysql["user"], cf.mysql["password"])

try:
    with connection.cursor() as cursor:
        cursor.execute('CREATE DATABASE IF NOT EXISTS gj001')    
 
finally:
    connection.close()
    

#creating gene table 
GENEsummary = "CREATE TABLE IF NOT EXISTS GENE
                (
                    accession      VARCHAR(100)     NOT NULL,\
                    gene     VARCHAR(80)     NOT NULL,\
                    product      VARCHAR(80)     NOT NULL,\
                    location      VARCHAR(80)     NOT NULL,\
                    PRIMARY KEY (accession))
                 )"
		
#creating CDS table     
CDSsummary = "CREATE TABLE IF NOT EXISTS CDS
                (
                    accession      VARCHAR(100)     NOT NULL,\
                    gene     VARCHAR(80)     NOT NULL,\
                    product      VARCHAR(80)     NOT NULL,\
                    location      VARCHAR(80)     NOT NULL,\
		    CDS      VARCHAR(80)     NOT NULL,\
                    PRIMARY KEY (accession))
                 )"
		
		
#creating DNA table     
DNAsummary = "CREATE TABLE IF NOT EXISTS DNA
                (
                    accession      VARCHAR(100)     NOT NULL,\
                    sequence     VARCHAR(80)     NOT NULL,\
                    aa_seq      VARCHAR(80)     NOT NULL,\
                    protein_id      VARCHAR(80)     NOT NULL,\
                    PRIMARY KEY (accession))
                 )"



        
# Create a tables
connection = pymysql.connect(cf.mysql["host"],
                             cf.mysql["user"],
                             cf.mysql["password"],
                             cf.mysql["db"],
                             cursorclass=pymysql.cursors.DictCursor)



try:
    with connection.cursor() as cursor:
        
        cursor.execute('DROP TABLE IF EXISTS DNA')
        cursor.execute('DROP TABLE IF EXISTS CDS')
        cursor.execute('DROP TABLE IF EXISTS GENE')
        
        cursor.execute(GENEsummary)
        cursor.execute(DNAsummary)
	cursor.execute(CDSsummary)

        connection.commit()


finally:
    connection.close() 

    
    
