#!/usr/bin/env python3


import sys
sys.path.insert(0, "..")
import db_parser
import config as cf
import pymysql.cursors


connection = pymysql.connect(cf.mysql["host"], cf.mysql["user"], cf.mysql["password"])

try:
    with connection.cursor() as cursor:
        cursor.execute('CREATE DATABASE IF NOT EXISTS gj001')    
 
finally:
    connection.close()
    


cursor.execute("CREATE TABLE IF NOT EXISTS GENE(\
                accession      VARCHAR(100)     NOT NULL,\
                 gene     VARCHAR(80)     NOT NULL,\
                 product      VARCHAR(80)     NOT NULL,\
                 location      VARCHAR(80)     NOT NULL,\
                 PRIMARY KEY (accession))"
               )







