#!/usr/bin/python3

import pymysql
import pymysql.cursors
import mysql.connector

def sqldbconnection():
# function to establish database connection
connection = pymysql.connect(dbhost="gj001", 
                                    port=8889, 
                                    dbuser="gj001", 
                                    dbpass="gj001", 
                                    dbname="pandora")
cursor = connection.cursor()

return connection 
